name: eslint-config

on:
  push:

env:
  PROJECT_DIR: eslint-config

jobs:
  build:
    runs-on: ubuntu-latest
    name: Node ${{ matrix.node }}
    strategy:
      matrix:
        node:
          - '14.18.1'

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.node }}
          bundler-cache: true
      - run: npm install
        working-directory: ${{ env.PROJECT_DIR }}
      - name: Run the build script
        run: npm run lint
        working-directory: ${{ env.PROJECT_DIR }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: contains(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v2
      - id: version-changed
        uses: tj-actions/changed-files@v20
        with:
          files: ${{ env.PROJECT_DIR }}/package.json
      - run: "echo release"
        if: steps.version-changed.outputs.any_changed == 'true'
